parameters:
    customer_management_framework.firewall_settings:
        pattern: ^/__customermanagementframework/webservice(/.*)?$
        stateless: true
        provider: pimcore_admin
        custom_authenticators:
            - CustomerManagementFrameworkBundle\Security\Authenticator\WebserviceAuthenticator
