_pimcore_customermanagementframework_backend:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin/customermanagementframework

_pimcore_customermanagementframework_backend_report:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Report"
    type:     annotation
    prefix:   /admin/customermanagementframework/report

_pimcore_customermanagementframework_rest:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Rest"
    type:     annotation
    prefix:   /webservice/cmf

_pimcore_customermanagementframework_preview:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Preview"
    type:     annotation
    prefix:   /__customermanagementframework



